version: 2
updates:
    -   package-ecosystem: "github-actions"
        directory: "/"
        schedule:
            interval: "daily"

    -   package-ecosystem: "composer"
        directory: "/"
        schedule:
            interval: "daily"
        allow:
            -   dependency-type: "direct"
        open-pull-requests-limit: 10
        rebase-strategy: "disabled"
        versioning-strategy: increase-if-necessary
