#!/bin/bash

## Description: Run PHP CodeSniffer inside the web container
## Usage: phpcs [flags] [args]
## Example: "ddev phpcs -i" or "ddev phpcs --help"

/var/www/html/vendor/bin/phpcs --colors -ps --standard=phpcs.xml $@
