#!/bin/bash

## Description: Run PHP CodeSniffer inside the web container
## Usage: phpcs [flags] [args]
## Example: "ddev phpcs -i" or "ddev phpcs modules/custom/my_module" or "ddev phpcs --help"

/var/www/html/vendor/bin/phpcs -ps --colors --standard=/var/www/html/phpcs.xml -- $@
