name: Main workflow

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    composer-build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v2

            -   name: Validate composer.json and composer.lock
                run: composer validate

            -   name: Install Composer packages
                run: composer install --no-ansi --no-interaction --no-progress --prefer-dist --optimize-autoloader

            -   name: List pull requests files
                uses: jitterbit/get-changed-files@v1
                if: ${{ github.event_name == 'pull_request' }}
                id: pr-files

            -   name: PHP CodeSniffer
                if: ${{ github.event_name == 'pull_request' }}
                run: ./vendor/bin/phpcs -ps --colors --standard=./phpcs.xml ${{ steps.pr-files.outputs.all }}
