name: PHP CodeSniffer

on: pull_request

jobs:
    phpcs:
        name: PHPCS
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout repository
                uses: actions/checkout@v2

            -
                uses: actions/download-artifact@v2
                with:
                    name: Drupal-Artifact
                    path: artifact.tar

            -
                name: Extract files
                run: |
                    tar -xvf artifact.tar --directory ./
                    ls -hAlF --color

            -
                name: PHP CodeSniffer
                uses: chekalsky/phpcs-action@v1
                with:
                    enable_warnings: true
                    phpcs_bin_path: './vendor/bin/phpcs'
                    installed_paths: '${{ github.workspace }}/vendor/drupal/coder/coder_sniffer/Drupal,${{ github.workspace }}/vendor/drupal/coder/coder_sniffer/DrupalPractice'
